### ISSUE TITLE
Walls/stairs/blocks becoming the "gneiss" version

### ISSUE THREAD

**Issue by Tukanen** [ExterminatorJeff/UndergroundBiomes#14]
I'm using the UndergroundBiomesConstructs-1.7.2-0.5e.jar

When placing wall or stairs (or any other stone-type-block from this mod) it become gneiss instead... it only seems to be looking like it, because if I mine it afterwards it returns to it's original type (i.e. black granite)

I figure it must be something with the IDs as all the other blocks have a .xxx suffix, whereas gneiss doesn't

**Comment by Zeno410** [comment]
It has something to do with getting information from tile entities. The programs stores the stone type in a tile entity. If it can't look it up, it defaults to the value "0" which happens to be Gneiss. Blocks dropped are correct because when the block is destroyed apparently it _can_ find the tile entity when it determines which block to drop.

This may be related to a long-standing odd behavior where my code gets called with an _adjacent_ tile entity.

It only happens with NEI as far as I know and since I don't use NEI I don't have a good way to fix it. Apparently it comes and goes with different NEI versions so I suspect it's something _they_ are doing wrong. I keep hoping it gets fixed in the course of their normal updates but it hasn't happened yet.

-----Original Message-----

**Comment by Tukanen** [comment]
Further testing reveals that it only seems to happen with NEI when it is set to show a tooltip of what you're seeing when mousing over something... just changing to that mode "wrecks" the blocks.
Gonna go to chickenbone with this issue then ;)
